# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sshauthorizedkey_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshauthorizedkey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
