language: python
sudo: false

services:
  - postgresql

env:
  - DB_HOST=localhost DB_NAME=bootloader_web_test DB_USER=postgres

python:
  - 2.7
  - 3.6

install:
    - pip install tox

script:
    - tox --skip-missing-interpreters
