dist: trusty
language: python
sudo: false

services:
  - postgresql

addons:
  postgresql: "9.6"

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
    - pip install tox

script:
    - tox -v
