---
apiVersion: v1
kind: Service
metadata:
  name: bootloader-web
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      name: http
  selector:
    app: bootloader-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bootloader-web
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: bootloader-web
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
        - name: rabbitmq
          image: rabbitmq-latest
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
        - name: bootloader-web
          image: teran/bootloader-web:latest
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          ports:
            - containerPort: 8000
              name: http
      volumes:
        - name: postgres-data
          hostPath:
            path: /srv/postgres-data
        - name: rabbitmq-data
          hostPath:
            path: /srv/rabbitmq-data
