---
apiVersion: v1
kind: Service
metadata:
  name: bootloader-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: bootloader-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bootloader-web
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: bootloader-web
    spec:
      containers:
        - name: bootloader-web
          image: teran/bootloader-web:latest
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          env:
            - name: BOOTLOADER_URL
              value: 'http://bootloader.services.svc.example.org/'
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: bootloader-keys
                  key: broker_url
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: bootloader-keys
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bootloader-keys
                  key: db_name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bootloader-keys
                  key: db_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bootloader-keys
                  key: db_user
          ports:
            - containerPort: 8000
              name: http
