---
apiVersion: v1
kind: Service
metadata:
  name: bootloader-web
spec:
  type: ClusterIP
  ports:
    - port: 5672
      protocol: TCP
      name: rabbitmq
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq-latest
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /srv/rabbitmq-data
