# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.6 on 2017-03-23 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Waiting for PXEBoot'), (3, 'Waiting for configuration request'), (4, 'Installation'), (5, 'Configuring'), (6, 'OS boot'), (7, 'Post actions')], default=1),
        ),
    ]
