# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 06:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
