# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.IntegerField(choices=[(1, 'Static'), (2, 'Template'), (3, 'Binary')], default=3),
        ),
    ]
