# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_file_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='accesstype',
            field=models.IntegerField(choices=[(1, 'API'), (2, 'Local')], default=1),
        ),
    ]
