# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_file_accesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='version',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('name', 'version')]),
        ),
    ]
