# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_auto_20170326_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='profile',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
