# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 06:48
from __future__ import unicode_literals

import deployments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_auto_20170330_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='token',
            field=models.CharField(default=deployments.models._generate_token, max_length=64),
        ),
    ]
