# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 06:37
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_deployment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=django_fsm.FSMField(default='unknown', max_length=50),
        ),
    ]
