# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0010_auto_20170414_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
