# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0016_auto_20170428_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
