# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0017_deployment_progress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('name', 'version', 'is_active')]),
        ),
    ]
