# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.6 on 2017-03-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=255, unique=True)),
                ('mac', models.CharField(max_length=15, unique=True)),
                ('groups', models.ManyToManyField(related_name='servers', to='core.Group')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='core.Location')),
            ],
        ),
    ]
