# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_server_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ipmi_browser_proto',
            field=models.IntegerField(choices=[(1, 'HTTP'), (2, 'HTTPS')], null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ipmi_host',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ipmi_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ipmi_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
