# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.6 on 2017-03-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170318_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ipmi_browser_proto',
            field=models.IntegerField(choices=[(None, 'None'), (1, 'http'), (2, 'https')], null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ipmi_host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='core.Location'),
        ),
    ]
