# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170320_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='mac',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
