# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interface_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='mac',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
