uwsgi:
  plugins: python
  uid: nobody
  gid: nogroup
  socket: 127.0.0.1:8000
  chdir: /opt/bootloader/web
  module: bootloader.wsgi:application
  master: True
  processes: 4
  vacuum: True
  max-requests: 5000
