# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.10.6 on 2017-03-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('mac', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=255, unique=True)),
                ('serial', models.CharField(max_length=255, null=True)),
                ('ipmi_host', models.CharField(max_length=255)),
                ('ipmi_username', models.CharField(max_length=255, null=True)),
                ('ipmi_password', models.CharField(max_length=255, null=True)),
                ('ipmi_browser_proto', models.IntegerField(choices=[(None, 'None'), (1, 'http'), (2, 'https')], null=True)),
                ('ipmi_browser_port', models.IntegerField(default=80)),
                ('groups', models.ManyToManyField(related_name='servers', to='servers.Group')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='servers.Location')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='servers.Server'),
        ),
    ]
