# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
