# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20170325_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='groups',
            new_name='labels',
        ),
        migrations.AddField(
            model_name='server',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
