# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20170417_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-created']},
        ),
    ]
