# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20170425_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ipmi_browser_proto',
            field=models.CharField(choices=[(None, 'None'), (1, 'http'), (2, 'https')], max_length=5, null=True),
        ),
    ]
