# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20170426_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
