# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_auto_20170428_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
