# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_auto_20170502_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('network', netfields.fields.CidrAddressField(max_length=43, unique=True)),
                ('gateway', netfields.fields.InetAddressField(max_length=39, unique=True)),
                ('nameserver', netfields.fields.InetAddressField(max_length=39)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='servers.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
