# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('queue', models.CharField(max_length=255, unique=True)),
                ('agent_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
